spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jpa?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    show-sql: true #??sql ??????
    hibernate:
      #create #?hibernate????? ???Springboot???????????
      #???create?update
      ddl-auto: update #???????????????????????????
